#!/usr/bin/env python2
#-*- coding: utf-8 -*-

from __future__ import print_function
import os
import sys
import errno
import hashlib
from optparse import OptionParser

if os.path.abspath(__file__).endswith('/scripts/mp3hash'):
    checkout_dir = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    sys.path.insert(0, checkout_dir)

import mp3hash


# hashlib.algorithms was included in python 2.7
ALGORITHMS = getattr(
    hashlib,
    'algorithms',
    ('md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512')
)


def error(msg):
    print('Error: ' + msg)


def list_algorithms():
    print('\n'.join(ALGORITHMS))


def main():
    opts, args, parser = parse_arguments()

    if opts.output:
        redirect_output(opts.output)

    if not args and not opts.list_algorithms:
        parser.print_help()
        error("\nInsufficient arguments")
        return errno.EINVAL

    if opts.maxbytes is not None and opts.maxbytes <= 0:
        parser.print_help()
        error("\nInvalid value for --maxbytes it should be a positive integer")
        return errno.EINVAL

    if opts.list_algorithms:
        list_algorithms()
        return 0

    if opts.algorithm not in ALGORITHMS:
        error("Unknown '{0}' algorithm. Available options are: {1}"
              .format(opts.algorithm, ", ".join(ALGORITHMS)))
        return errno.EINVAL

    for arg in args:
        path = os.path.realpath(arg)
        if not os.path.isfile(path):
            print("File at '{0}' does not exist or it is not a regular file"
                  .format(arg))
            continue

        hasher = hashlib.new(opts.algorithm)
        hash_result = mp3hash.mp3hash(path, maxbytes=opts.maxbytes, hasher=hasher)
        printfunc(arg=arg, path=path, hash_result=hash_result, hash_alg=opts.algorithm, opts=opts)

def legacy_print(path, hash_result, hash_only=False):
    # display file hash or just the hash
    if hash_only:
        filename = ''
    else:
        filename = ' ' + os.path.basename(path)

    print(hash_result + filename)

def tagged_print(arg, hash_result, hash_alg):
    print("MP3-%s (%s) = %s" % (hash_alg.upper(), arg, hash_result))

def printfunc(arg=None, path=None, hash_result=None, hash_alg=None, opts={}):
    if opts.tag:
        tagged_print(arg, hash_result, hash_alg)
    else:
        legacy_print(path, hash_result, hash_only=opts.hash)

def parse_arguments():
    parser = OptionParser()

    parser.add_option("-a", "--algorithm", default='sha1',
                      help="Hash algorithm to use. Default sha1.  "
                      "See --list-algorithms")

    parser.add_option("-l", "--list-algorithms", action="store_true",
                      default=False, help="List available algorithms")

    parser.add_option("-q", "--hash", action="store_true", default=False,
                      help="Print only hash information, no filename")

    parser.add_option("-m", "--maxbytes", type=int, default=None,
                      help="Max number of bytes of music to hash")

    parser.add_option("-o", "--output", default=False,
                      help="Redirect output to a file")

    parser.add_option("-t", "--tag", default=False, action="store_true",
                      help="Produce BSD-style tagged hash output")

    parser.set_usage("Usage: [options] FILE [FILE ..]")

    (opts, args) = parser.parse_args()

    return opts, args, parser


def redirect_output(path):
    stdout = sys.stdout
    try:
        sys.stdout = open(path, 'w')
    except IOError as err:
        sys.stdout = stdout
        error("Couldn't open {0}: {1}".format(path, err))
        sys.exit(errno.ENOENT)


if __name__ == "__main__":
    sys.exit(main())
